export { addSvgElement } from "./addSvgElement"
export { animate } from "./animate"
export { animatePath } from "./animatePath"
export { clear } from "./clear"
export { createAndAddCanvas } from "./createAndAddCanvas"
export { createAndAddSvg } from "./createAndAddSvg"
export { createCanvas } from "./createCanvas"
export { createSvg } from "./createSvg"
export { glob } from "./glob"
export { init as initGlob } from "./glob"
export { initCanvasStyle } from "./initCanvasStyle"
